--
-- XXL-JOB (PostgreSQL)
-- Copyright (c) 2015-present, xuxueli.
--
-- 使用前先创建数据库并连接到它，例如：
--   CREATE DATABASE xxl_job ENCODING 'UTF8';
--   \c xxl_job
--
-- 本脚本为本分支（sentino）从 MySQL 移植到 PostgreSQL 的版本：
--   AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--   DATETIME       -> TIMESTAMP
--   TINYINT        -> SMALLINT
--   MEDIUMTEXT     -> TEXT
--   列注释改为 COMMENT ON 语句

-- ================== job group and registry ==================

CREATE TABLE xxl_job_group
(
    id                    INT             GENERATED BY DEFAULT AS IDENTITY,
    app_name              VARCHAR(64)     NOT NULL,
    name                  VARCHAR(64)     NOT NULL,
    address_type          SMALLINT        NOT NULL DEFAULT 0,
    address_list          TEXT            DEFAULT NULL,
    access_token          VARCHAR(255)    DEFAULT NULL,
    update_time           TIMESTAMP       DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT i_app_name UNIQUE (app_name)
);
COMMENT ON COLUMN xxl_job_group.app_name      IS '执行器AppName';
COMMENT ON COLUMN xxl_job_group.name          IS '执行器名称';
COMMENT ON COLUMN xxl_job_group.address_type  IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN xxl_job_group.address_list  IS '执行器地址列表，多地址逗号分隔';
COMMENT ON COLUMN xxl_job_group.access_token  IS '执行器AccessToken';

CREATE TABLE xxl_job_registry
(
    id                    BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    registry_group        VARCHAR(50)     NOT NULL,
    registry_key          VARCHAR(255)    NOT NULL,
    registry_value        VARCHAR(255)    NOT NULL,
    update_time           TIMESTAMP       DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT i_g_k_v UNIQUE (registry_group, registry_key, registry_value)
);

-- ================== job info ==================

CREATE TABLE xxl_job_info
(
    id                        INT             GENERATED BY DEFAULT AS IDENTITY,
    job_group                 INT             NOT NULL,
    name                      VARCHAR(255)    NOT NULL,
    author                    VARCHAR(64)     DEFAULT NULL,
    alarm_email               VARCHAR(255)    DEFAULT NULL,
    schedule_type             VARCHAR(50)     NOT NULL DEFAULT 'NONE',
    schedule_conf             VARCHAR(128)    DEFAULT NULL,
    schedule_timezone         VARCHAR(64)     DEFAULT NULL,
    misfire_strategy          VARCHAR(50)     NOT NULL DEFAULT 'DO_NOTHING',
    executor_route_strategy   VARCHAR(50)     DEFAULT NULL,
    executor_handler          VARCHAR(255)    DEFAULT NULL,
    executor_param            TEXT            DEFAULT NULL,
    executor_block_strategy   VARCHAR(50)     DEFAULT NULL,
    executor_timeout          INT             NOT NULL DEFAULT 0,
    executor_fail_retry_count INT             NOT NULL DEFAULT 0,
    child_jobid               VARCHAR(255)    DEFAULT NULL,
    trigger_status            SMALLINT        NOT NULL DEFAULT 0,
    trigger_last_time         BIGINT          NOT NULL DEFAULT 0,
    trigger_next_time         BIGINT          NOT NULL DEFAULT 0,
    add_time                  TIMESTAMP       DEFAULT NULL,
    update_time               TIMESTAMP       DEFAULT NULL,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN xxl_job_info.job_group                 IS '执行器主键ID';
COMMENT ON COLUMN xxl_job_info.name                      IS '任务名称';
COMMENT ON COLUMN xxl_job_info.author                    IS '作者';
COMMENT ON COLUMN xxl_job_info.alarm_email               IS '报警邮件';
COMMENT ON COLUMN xxl_job_info.schedule_type             IS '调度类型';
COMMENT ON COLUMN xxl_job_info.schedule_conf             IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN xxl_job_info.schedule_timezone         IS '调度时区，CRON类型生效，为空则使用调度中心默认时区';
COMMENT ON COLUMN xxl_job_info.misfire_strategy          IS '调度过期策略';
COMMENT ON COLUMN xxl_job_info.executor_route_strategy   IS '执行器路由策略';
COMMENT ON COLUMN xxl_job_info.executor_handler          IS '任务handler';
COMMENT ON COLUMN xxl_job_info.executor_param            IS '任务参数';
COMMENT ON COLUMN xxl_job_info.executor_block_strategy   IS '阻塞处理策略';
COMMENT ON COLUMN xxl_job_info.executor_timeout          IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN xxl_job_info.executor_fail_retry_count IS '失败重试次数';
COMMENT ON COLUMN xxl_job_info.child_jobid               IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN xxl_job_info.trigger_status            IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN xxl_job_info.trigger_last_time         IS '上次调度时间';
COMMENT ON COLUMN xxl_job_info.trigger_next_time         IS '下次调度时间';

-- ================== job log and report ==================

CREATE TABLE xxl_job_log
(
    id                        BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    job_group                 INT             NOT NULL,
    job_id                    INT             NOT NULL,
    executor_address          VARCHAR(255)    DEFAULT NULL,
    executor_handler          VARCHAR(255)    DEFAULT NULL,
    executor_param            TEXT            DEFAULT NULL,
    executor_sharding_param   VARCHAR(20)     DEFAULT NULL,
    executor_fail_retry_count INT             NOT NULL DEFAULT 0,
    trigger_time              TIMESTAMP       DEFAULT NULL,
    trigger_code              INT             NOT NULL,
    trigger_msg               TEXT            DEFAULT NULL,
    handle_time               TIMESTAMP       DEFAULT NULL,
    handle_code               INT             NOT NULL,
    handle_msg                TEXT            DEFAULT NULL,
    alarm_status              SMALLINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
CREATE INDEX i_trigger_time ON xxl_job_log (trigger_time);
CREATE INDEX i_handle_code  ON xxl_job_log (handle_code);
CREATE INDEX i_job_group    ON xxl_job_log (job_group);
CREATE INDEX i_job_id       ON xxl_job_log (job_id);
COMMENT ON COLUMN xxl_job_log.job_group                 IS '执行器主键ID';
COMMENT ON COLUMN xxl_job_log.job_id                    IS '任务，主键ID';
COMMENT ON COLUMN xxl_job_log.executor_address          IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN xxl_job_log.executor_handler          IS '任务handler';
COMMENT ON COLUMN xxl_job_log.executor_param            IS '任务参数';
COMMENT ON COLUMN xxl_job_log.executor_sharding_param   IS '任务分片参数，格式如 1/2';
COMMENT ON COLUMN xxl_job_log.executor_fail_retry_count IS '失败重试次数';
COMMENT ON COLUMN xxl_job_log.trigger_time              IS '调度-时间';
COMMENT ON COLUMN xxl_job_log.trigger_code              IS '调度-结果';
COMMENT ON COLUMN xxl_job_log.trigger_msg               IS '调度-日志';
COMMENT ON COLUMN xxl_job_log.handle_time               IS '执行-时间';
COMMENT ON COLUMN xxl_job_log.handle_code               IS '执行-状态';
COMMENT ON COLUMN xxl_job_log.handle_msg                IS '执行-日志';
COMMENT ON COLUMN xxl_job_log.alarm_status              IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

CREATE TABLE xxl_job_log_report
(
    id                    INT             GENERATED BY DEFAULT AS IDENTITY,
    trigger_day           TIMESTAMP       DEFAULT NULL,
    running_count         INT             NOT NULL DEFAULT 0,
    suc_count             INT             NOT NULL DEFAULT 0,
    fail_count            INT             NOT NULL DEFAULT 0,
    update_time           TIMESTAMP       DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT i_trigger_day UNIQUE (trigger_day)
);
COMMENT ON COLUMN xxl_job_log_report.trigger_day    IS '调度-时间';
COMMENT ON COLUMN xxl_job_log_report.running_count  IS '运行中-日志数量';
COMMENT ON COLUMN xxl_job_log_report.suc_count      IS '执行成功-日志数量';
COMMENT ON COLUMN xxl_job_log_report.fail_count     IS '执行失败-日志数量';

-- ================== lock ==================

CREATE TABLE xxl_job_lock
(
    lock_name VARCHAR(50) NOT NULL,
    PRIMARY KEY (lock_name)
);
COMMENT ON COLUMN xxl_job_lock.lock_name IS '锁名称';

-- ================== user ==================

CREATE TABLE xxl_job_user
(
    id                INT             GENERATED BY DEFAULT AS IDENTITY,
    username          VARCHAR(50)     NOT NULL,
    password          VARCHAR(100)    NOT NULL,
    token             VARCHAR(100)    DEFAULT NULL,
    role              SMALLINT        NOT NULL,
    permission        VARCHAR(255)    DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT i_username UNIQUE (username)
);
COMMENT ON COLUMN xxl_job_user.username    IS '账号';
COMMENT ON COLUMN xxl_job_user.password    IS '密码加密信息';
COMMENT ON COLUMN xxl_job_user.token       IS '登录token';
COMMENT ON COLUMN xxl_job_user.role        IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN xxl_job_user.permission  IS '权限：执行器ID列表，多个逗号分割';


-- ================== for default data ==================

BEGIN;

INSERT INTO xxl_job_group(id, app_name, name, address_type, address_list, access_token, update_time)
    VALUES (1, 'xxl-job-executor-sample', '通用执行器Sample', 0,  NULL, 'default_token', now()),
           (2, 'xxl-job-executor-sample-ai', 'AI执行器Sample', 0, NULL, 'default_token', now());

INSERT INTO xxl_job_info(id, job_group, name, add_time, update_time, author, alarm_email,
                         schedule_type, schedule_conf, misfire_strategy, executor_route_strategy,
                         executor_handler, executor_param, executor_block_strategy, executor_timeout,
                         executor_fail_retry_count, child_jobid)
VALUES (1, 1, '示例任务01', now(), now(), 'XXL', '', 'CRON', '0 0 0 * * ? *',
        'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, ''),
       (2, 2, 'Ollama示例任务', now(), now(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'ollamaJobHandler', '{
    "input": "Java实现二叉树层序遍历",
    "prompt": "你是一个研发工程师，擅长解决技术类问题。",
    "model": "qwen3.5:0.8b"
}', 'SERIAL_EXECUTION', 0, 0, ''),
       (3, 2, 'Dify示例任务', now(), now(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'difyWorkflowJobHandler', '{
    "inputs":{
        "input":"查询班级各学科前三名"
    },
    "user": "xxl-job",
    "baseUrl": "http://localhost/v1",
    "apiKey": "app-OUVgNUOQRIMokfmuJvBJoUTN"
}', 'SERIAL_EXECUTION', 0, 0, ''),
       (4, 2, 'OpenClaw示例任务', now(), now(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'openClawJobHandler', '{
    "input": "查看下上海今天得天气，给出出游建议",
    "prompt": "你是一个出游助手，擅长做旅游规划"
}', 'SERIAL_EXECUTION', 0, 0, '');

INSERT INTO xxl_job_user(id, username, password, role, permission)
VALUES (1, 'admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 1, NULL);

INSERT INTO xxl_job_lock (lock_name)
VALUES ('schedule_lock');

-- 默认数据显式指定了主键，需要把 identity 序列推进到当前最大值，否则后续插入会主键冲突
SELECT setval(pg_get_serial_sequence('xxl_job_group', 'id'), (SELECT max(id) FROM xxl_job_group));
SELECT setval(pg_get_serial_sequence('xxl_job_info',  'id'), (SELECT max(id) FROM xxl_job_info));
SELECT setval(pg_get_serial_sequence('xxl_job_user',  'id'), (SELECT max(id) FROM xxl_job_user));

COMMIT;
